### ISSUE TITLE
Would it be possible to have different options between Info() and Error()

### ISSUE THREAD

**Issue by StephaneBunel** [go-logr/zerologr#16]
```
func main() {
	zl := zerolog.New(os.Stderr)
	zl = zl.With().
		Caller().
		Timestamp().
		Logger()
	logger := zerologr.New(&zl)

```

I don't need the caller() option for regular Info() log, I want it only for Error().
Is it possible without creating two different logger ?

**Comment by hn8** [comment]
@StephaneBunel No, but you can fork zerolgr and only call CallerSkipFrame for your Error()
https://github.com/go-logr/zerologr/blob/master/zerologr.go#L114
