### ISSUE TITLE
Enabled() returns true when it should not

### ISSUE THREAD

**Issue by uablrek** [go-logr/zerologr#19]
I tried the trick described in https://github.com/go-logr/logr/issues/149#issuecomment-1231513709 but it doesn't work for zerologr.

Here is a slightly altered example;
```go
package main

import (
	"fmt"
	"os"

	"github.com/go-logr/logr"
	"github.com/go-logr/zerologr"
	"github.com/rs/zerolog"
)

func main() {
	zerolog.TimeFieldFormat = zerolog.TimeFormatUnixMs
	zerologr.NameFieldName = "logger"
	zerologr.NameSeparator = "/"

	zl := zerolog.New(os.Stderr)
	zl = zl.With().Caller().Timestamp().Logger().Level(zerolog.InfoLevel)
	var log logr.Logger = zerologr.New(&zl)
	lvl := 2
	fmt.Println("Lvl", lvl, "Enabled", log.V(lvl).Enabled())
	log.Info("Logr in action!", "the answer", 42)
}
// output: Lvl 2 Enabled true
```
https://go.dev/play/p/sR1JXKaxgPs

When the level is `zerolog.InfoLevel` log.V(2).Enabled() should return `false`.

**Comment by pohly** [comment]
CC @hn8

**Comment by hn8** [comment]
@uablrek You don't need to call Enabled() since it is already called inside Info().
https://github.com/go-logr/logr/blob/master/logr.go#L257

**Comment by uablrek** [comment]
The reason is explained in https://github.com/go-logr/logr/issues/149

**Comment by uablrek** [comment]
ok

**Comment by pohly** [comment]
> zerologr Enabled() is optimized for exactly the same reason to avoid necessary call where zerolog has the same check internally

The downside is that the pattern from https://github.com/go-logr/logr/issues/149 becomes less efficient. It's not wrong, it just doesn't skip evaluating all key/value parameters as it does with other logger backends.

**Comment by pohly** [comment]
However, there is another pattern in Kubernetes where the zerologr behavior is wrong:
```
loggerV := logger.V(6)
if loggerV.Enabled() {
    loggerV.Info("Log call with many details", "x", 1, "y", 2)
} else {
   logger.V(5).Info("Log call with less details", "x", 1)
}
```

The intention is to log some additional, large values (in some real examples it's the content of a config file) only when the log level is high. With zerologr, the extra values always get logged.

I consider this a bug in zerologr because it doesn't implement the logr API as intended and expected by users.

**Comment by hn8** [comment]
@pohly zerologr.Enabled() output is correct as long as level is set by logr.V() instead of changing zerolog default global level. It is more preferrable to use logr.V() ro set level since it is local and customizable.

**Comment by pohly** [comment]
So the part that is wrong in the example above is the `.Level(zerolog.InfoLevel)`?

If that isn't called out somewhere, then it probably would be a worthwhile addition to the documentation.
