### ISSUE TITLE
Cannot log with verbosity > 2

### ISSUE THREAD

**Issue by byatesrae** [go-logr/zerologr#20]
When logging at a verbosity > 2 no log messages appear, despite configuring zerolog's minimum accepted level.

I can see logging is short circuited [here](https://github.com/go-logr/zerologr/blob/8ee78188f4bd4ff1cb5f9ebaf02f455a75cb2e7a/zerologr.go#L89) but I'm not sure why given [logr's philosophy](https://github.com/go-logr/logr#how-do-i-choose-my-v-levels) seems to imply we choose verbosity based on the applications needs.

```
package main

import (
	"os"

	"github.com/go-logr/zerologr"
	"github.com/rs/zerolog"
)

func main() {
	zLogger := zerolog.New(os.Stderr)
	zLogger = zLogger.Level(-10)
	zerolog.SetGlobalLevel(-10)

	zLogger.WithLevel(-1).Msg("zLogger -1") // trace
	zLogger.WithLevel(-2).Msg("zLogger -2") // less than trace

	logger := zerologr.New(&zLogger)
	logger.V(2).Info("logger v2")
	logger.V(3).Info("logger v3")
}
```
[Go playground.](https://go.dev/play/p/mtqMPkAcfrW)

Expected output:

> {"level":"trace","message":"zLogger -1"}
> {"level":"-2","message":"zLogger -2"}
> {"level":"trace","v":2,"message":"logger v2"}
> {"level":"-2","v":3,"message":"logger v3"}

Actual output:

> {"level":"trace","message":"zLogger -1"}
> {"level":"-2","message":"zLogger -2"}
> {"level":"trace","v":2,"message":"logger v2"}

**Comment by hn8** [comment]
@byatesrae When using with logr, it is preferrable to avoid calling zerolog.SetGlobalLevel() and use logr.V() instead, so it is safe to use many packages depending on logr. Currently, logr.V() only supports level addition.
https://github.com/go-logr/logr/blob/master/logr.go#L286-L290

**Comment by byatesrae** [comment]
Thanks @hn8, use of `zerolog.SetGlobalLevel()` aside how might we log with a verbosity > 2 using `logr.V()`? From my example I'm using `logr.V(2)` & `logr.V(3)` yet no log entry is created when using `logr.V(3)`.

Here's a simplified example:
```
package main

import (
	"os"

	"github.com/go-logr/zerologr"
	"github.com/rs/zerolog"
)

func main() {
	zLogger := zerolog.New(os.Stderr)
	logger := zerologr.New(&zLogger)

	logger.V(2).Info("logger v2")
	logger.V(3).Info("logger v3")
	logger.V(4).Info("logger v4")
	logger.V(5).Info("logger v5")
}
```
[Go Playground](https://go.dev/play/p/mOweltM7_iG)

Expected output:
> {"level":"trace","v":2,"message":"logger v2"}
> {"level":"-1","v":3,"message":"logger v3"}
> {"level":"-2","v":4,"message":"logger v4"}
> {"level":"-3","v":5,"message":"logger v5"}

Actual output:
> {"level":"trace","v":2,"message":"logger v2"}

**Comment by hn8** [comment]
@byatesrae zerologr's log level range is limited by underlying implementation of zerolog and logr. zerologr only supports these levels: https://github.com/rs/zerolog#leveled-logging. And logr's philosophy removes warn/fatal/panic. So there are only 3 available logr levels: 0 for info, 1 for debug, 2 for trace.

**Comment by ajanata** [comment]
> @byatesrae When using with logr, it is preferrable to avoid calling zerolog.SetGlobalLevel() and use logr.V() instead, so it is safe to use many packages depending on logr. Currently, logr.V() only supports level addition. https://github.com/go-logr/logr/blob/master/logr.go#L286-L290

Our project uses zerolog as the primary logger, and a library we're using uses logr instead. We want to keep all configuration in zerolog, however we are unable to get debug logs out of the library because of this limitation. What is the suggested workaround in this case?

**Comment by tonglil** [comment]
@ajanata you can still get Zerolog to print `debug` level logs: https://go.dev/play/p/aoJrlyE494C

**Comment by tonglil** [comment]
I will make a PR to document that Zerolog is limited to printing up to V(2) verbosity.

**Comment by hn8** [comment]
@ajanata In zerolog, using levels more verbose than TraceLevel is an undocumented feature. Would you please share what value you pass into zerolog.SetGlobalLevel() and logr.V()?

**Comment by hn8** [comment]
@tonglil undocumented zerolog levels do not support LevelSampler and LevelHook, and likely never will since they are struct. zapr may be the better choice than zerologr if higher verbosity is needed.

**Comment by thockin** [comment]
The whole point of https://github.com/rs/zerolog/pull/350/files was to allow higher V levels.  If zerologr can't make that work, it's not really a very useful logr implementation, IMO.

**Comment by hn8** [comment]
It is possible but not enabled by default in new PR. Explained here https://github.com/go-logr/zerologr/pull/25#issuecomment-1407908245

**Comment by ajanata** [comment]
> @ajanata In zerolog, using levels more verbose than TraceLevel is an undocumented feature. Would you please share what value you pass into zerolog.SetGlobalLevel() and logr.V()? Or do you pass in zerolog.Logger with different level in zelologr.New()?

Apologies, I suppose I should open a bug with opentelemetry-go, since [they use `V(5)` for debug](https://github.com/open-telemetry/opentelemetry-go/blob/0617172787699be1d778bad0bc5baa49ad9a2b58/internal/global/internal_logging.go#L61-L63). We are using the standard debug level in zerolog.

**Comment by hn8** [comment]
@ajanata You can now use SetMaxV to adjust global level of Zerolog in zerologr v1.2.3.
